"""irag.export — project the database into generated context files.

Memory is data with a prose projection: the context file agents read is a
build artifact, regenerated from the current revisions, never hand-edited.
Two identical projections are written: CLAUDE.md (read natively by Claude
Code) and AGENTS.md (the cross-tool convention read by Codex, Antigravity,
and other agents). Redundant by design — same content, whichever file the
agent's harness looks for.
"""
from __future__ import annotations

import sqlite3
from pathlib import Path

from . import db


def export(conn: sqlite3.Connection, cfg: dict, repo: Path,
           out_name: str = "CLAUDE.md") -> Path:
    """Write CLAUDE.md + AGENTS.md at the repo root from current page
    bodies. Returns the CLAUDE.md path (the primary artifact)."""
    from . import __version__

    threshold = int(cfg["staleness"]["threshold"])
    # folder + log pages only: file-level detail lives in 'irag context'
    # and 'irag map'; CLAUDE.md stays a readable overview
    pages = conn.execute(
        """SELECT * FROM pages WHERE current_revision_id IS NOT NULL
           AND page_type IN ('folder', 'overview', 'decisions', 'lessons')
           ORDER BY (subject_id='.') DESC, subject_id"""
    ).fetchall()

    lines = [
        f"<!-- generated by irag v{__version__} — do not edit; run 'irag export' -->",
        "",
    ]
    for page in pages:
        body = db.current_body(conn, page["page_id"]) or ""
        if not body.lstrip().startswith("#"):
            lines.append(f"## {page['title']}")
        warn = []
        if page["staleness_score"] > threshold:
            warn.append(f"stale (score {page['staleness_score']})")
        open_c = db.open_contradiction_count(conn, page["page_id"])
        if open_c:
            warn.append(f"{open_c} open contradiction(s)")
        if warn:
            lines.append(f"> ⚠ {', '.join(warn)} — verify against the code.")
        lines.append(body)
        lines.append("")

    lines += [
        "## Working with irag (instructions for AI agents)",
        "",
        "This project's memory is managed by irag. **Before you grep, "
        "glob, or read files to understand this project, use the "
        "commands below instead** — the memory has already paid the "
        "token cost of exploring this codebase, so spending your own "
        "tokens re-discovering it is redundant work:",
        "",
        "- `irag context --open <file> --query \"<task>\"` — ranked, "
        "budgeted context for the task at hand",
        "- `irag search <query>` — SQL search: instant full-text lookup "
        "across all page versions (FTS5, no tokens)",
        "- `irag ask \"<question>\"` — AI search: the knowledge base "
        "answers a question, with page citations",
        "- `irag map [path]` / `irag impact <path>` — code map and blast "
        "radius (deterministic, always current)",
        "- `irag why \"<claim>\"` — trace any claim to its source change",
        "- `irag recap` — \"previously on this project\": what the last "
        "conversations did and changed (also auto-injected at session "
        "start)",
        "",
        "REQUIRED after you finish making or editing files: run "
        "`irag update`. This ingests your changes and synthesizes a new "
        "version of every affected file and folder page, fact-checks "
        "them, and regenerates this document. Do not skip it — it is how "
        "the knowledge base stays true.",
        "",
        "**Log this conversation.** Every coding session is recorded as "
        "a row in the project diary — when it ran, which files changed, "
        "and a summary — so the next session (or a fresh chat) can "
        "resume in ~150 tokens instead of re-exploring. Claude Code with "
        "`irag claude-setup` installed does this automatically via hooks "
        "— skip the rest of this paragraph. Any other agent must do it "
        "manually: run `irag session-begin` as your first action in a "
        "conversation and `irag session-end` as your last, before the "
        "conversation closes. Do not skip this — it is the only thing "
        "that makes `irag recap` and `irag sessions` work for whoever "
        "picks this project up next. `irag sessions --json` (or the "
        "dashboard's Sessions tab) lists every past conversation with "
        "exactly what changed in each.",
        "",
        "Record what you learn so future sessions know it:",
        "",
        "- `irag record-decision \"<decision and why>\" --module <m>` — "
        "architectural/tooling choices",
        "- `irag learn \"<gotcha or lesson>\" --module <m>` — pitfalls, "
        "fixes, constraints discovered while working",
        "",
        "When memory and code disagree: THE CODE IS THE TRUTH. Pages "
        "marked ⚠ have open contradictions — check `irag contradictions` "
        "to see the exact claims, verify against the code, and either fix "
        "the code (then `irag update`) or `irag resolve <id> --notes "
        "\"...\"` if the flag is spurious. `irag status --json` gives "
        "the current health of this knowledge base at any time.",
        "",
        "This document reflects the last `irag update`. If you have made "
        "changes since, the file pages may lag; run `irag update` or use "
        "`irag map` (always current, parsed from code) for structure. "
        "Never edit this file by hand; it is regenerated by `irag export`.",
        "",
    ]
    text = "\n".join(lines)
    out_path = repo / out_name
    out_path.write_text(text, encoding="utf-8")
    if out_name == "CLAUDE.md":
        (repo / "AGENTS.md").write_text(text, encoding="utf-8")
    return out_path
