"""irag.obsidian — project the database into an Obsidian vault.

Same principle as ``irag export``: memory is data with a prose projection.
Here the projection is a folder of markdown notes — one per page, one per
revision — wired with wikilinks so Obsidian's graph view renders the
project's knowledge structure. The vault is a disposable build artifact:
it is wiped and rebuilt on every run (guarded by a marker file so irag
never deletes a folder it didn't create).

Graph anatomy:
  * module notes  — the current pages, linked to parents/children and
                    any rows in the ``links`` table
  * version notes — every revision, tagged #version, chained prev/next;
                    filter them out live with `-tag:#version`
  * contradiction callouts — open contradictions render as warning
                    callouts on the page and as #contradiction notes
  * _meta/        — stats, open contradictions, graph setup instructions
"""
from __future__ import annotations

import hashlib
import re
import shutil
import sqlite3
from pathlib import Path

from . import db

MARKER = ".irag-vault"


# Distinct subjects can flatten to the same note name: this collapses every
# run of non-[\w.-] to "-", so `src/a.py` and `src-a.py` both become
# `src-a.py`, as do `a/b/c.py`, `a-b/c.py` and `a/b-c.py`. One page then
# overwrote the other in the vault - silently, and leaving the survivor's
# content filed under a name matching the file it is NOT. `_SLUG_MAP` is built
# once per export from the full subject set and disambiguates only the groups
# that actually collide, so ordinary names stay clean.
_SLUG_MAP: dict[str, str] = {}


def _base_slug(subject_id: str) -> str:
    if subject_id == ".":
        return "root"
    return re.sub(r"[^\w.-]+", "-", subject_id).strip("-")


def _build_slug_map(subjects) -> dict[str, str]:
    """subject -> unique note name. Every member of a colliding group is
    suffixed, not just the later ones, so the result does not depend on which
    page happened to be seen first."""
    grouped: dict[str, list[str]] = {}
    for sid in subjects:
        grouped.setdefault(_base_slug(sid), []).append(sid)
    out: dict[str, str] = {}
    for base, members in grouped.items():
        if len(members) == 1:
            out[members[0]] = base
            continue
        for sid in members:
            digest = hashlib.sha1(sid.encode("utf-8")).hexdigest()[:6]
            out[sid] = f"{base}-{digest}"
    return out


def _slug(subject_id: str) -> str:
    """Filesystem/wikilink-safe note name for a subject."""
    mapped = _SLUG_MAP.get(subject_id)
    return mapped if mapped else _base_slug(subject_id)


def _fm(pairs: dict) -> str:
    """Render YAML frontmatter."""
    lines = ["---"]
    for key, value in pairs.items():
        if isinstance(value, list):
            lines.append(f"{key}: [{', '.join(str(v) for v in value)}]")
        else:
            lines.append(f"{key}: {value}")
    lines.append("---")
    return "\n".join(lines)


def _wipe(vault: Path) -> None:
    if vault.exists():
        if not (vault / MARKER).exists():
            raise SystemExit(
                f"irag: {vault} exists but was not created by irag "
                f"(missing {MARKER}) — refusing to delete it. "
                "Choose another --out or remove it yourself."
            )
        shutil.rmtree(vault)
    vault.mkdir(parents=True)
    (vault / MARKER).write_text("generated by irag — safe to delete\n")


def export_vault(conn: sqlite3.Connection, cfg: dict, repo: Path,
                 out: Path | None = None, versions: bool = True) -> Path:
    """Build the vault. Returns its path."""
    from . import __version__

    vault = out or (repo / "irag_vault")
    _wipe(vault)
    (vault / "Modules").mkdir()
    (vault / "_meta").mkdir()
    if versions:
        (vault / "_versions").mkdir()

    threshold = int(cfg["staleness"]["threshold"])
    pages = conn.execute(
        "SELECT * FROM pages WHERE COALESCE(deleted_at,'')='' "
        "ORDER BY subject_id").fetchall()
    subjects = {p["subject_id"] for p in pages}
    # resolve note names before anything is written, so notes and the
    # wikilinks pointing at them agree
    global _SLUG_MAP
    _SLUG_MAP = _build_slug_map(subjects)
    by_id = {p["page_id"]: p for p in pages}

    # explicit links from the links table
    link_rows = conn.execute("SELECT * FROM links").fetchall()
    explicit: dict[int, set[int]] = {}
    for row in link_rows:
        explicit.setdefault(row["source_page_id"], set()).add(
            row["target_page_id"])
        explicit.setdefault(row["target_page_id"], set()).add(
            row["source_page_id"])

    # ------------------------------------------------------------------
    # module notes
    # ------------------------------------------------------------------
    for page in pages:
        sid = page["subject_id"]
        slug = _slug(sid)
        open_contras = conn.execute(
            "SELECT * FROM contradictions "
            "WHERE page_id=? AND resolved_at IS NULL ORDER BY severity",
            (page["page_id"],),
        ).fetchall()
        version_count = conn.execute(
            "SELECT COUNT(*) c FROM revisions WHERE page_id=?",
            (page["page_id"],),
        ).fetchone()["c"]
        current_v = conn.execute(
            "SELECT version_number v FROM revisions WHERE revision_id=?",
            (page["current_revision_id"],),
        ).fetchone() if page["current_revision_id"] else None

        tags = [page["page_type"] or "page"]
        if page["staleness_score"] > threshold:
            tags.append("stale")
        if open_contras:
            tags.append("contradicted")
        if page["pinned"]:
            tags.append("pinned")

        parts = [_fm({
            "subject": sid,
            "type": page["page_type"],
            "version": current_v["v"] if current_v else 0,
            "staleness": page["staleness_score"],
            "confidence": page["confidence"],
            "updated": page["last_updated_at"],
            "tags": tags,
        }), ""]

        for c in open_contras:
            parts.append(f"> [!warning] Open contradiction ({c['severity']})")
            parts.append(f"> **Claim:** {c['claim']}")
            parts.append(f"> **Truth:** {c['truth']}")
            parts.append("")

        body = db.current_body(conn, page["page_id"])
        parts.append(body if body else
                     "*No revision yet — run `irag synthesize`.*")

        # relationship links: parent, children, explicit
        rel = []
        if sid != ".":
            ancestor = sid
            parent = None
            while "/" in ancestor:
                ancestor = ancestor.rsplit("/", 1)[0]
                if ancestor in subjects:
                    parent = ancestor
                    break
            if parent is None and "." in subjects:
                parent = "."
            if parent:
                rel.append(f"- parent: [[{_slug(parent)}]]")
        if sid == ".":
            children = sorted(s for s in subjects
                              if s != "." and "/" not in s)
        else:
            prefix = sid + "/"
            children = sorted(
                s for s in subjects
                if s.startswith(prefix) and "/" not in s[len(prefix):])
        rel.extend(f"- child: [[{_slug(c)}]]" for c in children)
        for other_id in sorted(explicit.get(page["page_id"], ())):
            other = by_id.get(other_id)
            if other:
                rel.append(f"- related: [[{_slug(other['subject_id'])}]]")
        if rel:
            parts += ["", "## Links", *rel]

        if versions and version_count:
            parts += ["", "## History",
                      f"- [[v{version_count} {slug}]] (current)"]
            if version_count > 1:
                parts.append(f"- [[v1 {slug}]] (first)")

        (vault / "Modules" / f"{slug}.md").write_text(
            "\n".join(parts), encoding="utf-8")

    # ------------------------------------------------------------------
    # version notes (chained prev/next, tagged #version)
    # ------------------------------------------------------------------
    if versions:
        for page in pages:
            slug = _slug(page["subject_id"])
            revs = conn.execute(
                "SELECT * FROM revisions WHERE page_id=? ORDER BY version_number",
                (page["page_id"],),
            ).fetchall()
            for i, rev in enumerate(revs):
                ev = conn.execute(
                    "SELECT * FROM events WHERE event_id=?",
                    (rev["triggered_by_event_id"],),
                ).fetchone() if rev["triggered_by_event_id"] else None
                provenance = "human"
                if ev:
                    provenance = ev["event_type"]
                    if ev["source_ref"]:
                        provenance += f" {ev['source_ref'][:10]}"
                parts = [_fm({
                    "subject": page["subject_id"],
                    "version": rev["version_number"],
                    "created": rev["created_at"],
                    "model": rev["llm_model_used"] or "unknown",
                    "trigger": provenance,
                    "tags": ["version"],
                }), "", f"page: [[{slug}]]"]
                if i > 0:
                    parts.append(f"prev: [[v{revs[i-1]['version_number']} {slug}]]")
                if i < len(revs) - 1:
                    parts.append(f"next: [[v{revs[i+1]['version_number']} {slug}]]")
                if rev["change_summary"]:
                    parts += ["", f"> {rev['change_summary']}"]
                if ev and ev["payload"]:
                    payload = db.json_object(ev["payload"])
                    if payload.get("message"):
                        parts.append(f"> commit: {payload['message']}")
                parts += ["", "---", "", rev["body_markdown"]]
                name = f"v{rev['version_number']} {slug}.md"
                (vault / "_versions" / name).write_text(
                    "\n".join(parts), encoding="utf-8")

    # ------------------------------------------------------------------
    # _meta: stats, contradictions, graph instructions, index
    # ------------------------------------------------------------------
    totals = conn.execute(
        """SELECT
             (SELECT COUNT(*) FROM pages
               WHERE COALESCE(deleted_at,'')='')                         AS pages,
             (SELECT COUNT(*) FROM revisions)                            AS revisions,
             (SELECT COALESCE(SUM(tokens_used),0) FROM revisions)        AS tokens,
             (SELECT COUNT(*) FROM events)                               AS events,
             (SELECT COUNT(*) FROM events WHERE status='queued')         AS queued,
             (SELECT COUNT(*) FROM contradictions)                       AS contras,
             (SELECT COUNT(*) FROM contradictions c JOIN pages p
               ON p.page_id=c.page_id WHERE c.resolved_at IS NULL
               AND COALESCE(p.deleted_at,'')='')
                                                                         AS open_contras
        """).fetchone()
    stale_table = "\n".join(
        f"| {p['subject_id']} | {p['staleness_score']} | "
        f"{'yes' if p['staleness_score'] >= threshold else 'no'} |"
        for p in sorted(pages, key=lambda r: -r["staleness_score"])
    )
    (vault / "_meta" / "stats.md").write_text(f"""# irag vault stats

Generated by irag v{__version__}.

| metric | value |
|---|---|
| pages | {totals['pages']} |
| revisions | {totals['revisions']} |
| est. tokens spent | {totals['tokens']} |
| events (queued) | {totals['events']} ({totals['queued']}) |
| contradictions (open) | {totals['contras']} ({totals['open_contras']}) |

## Staleness

| module | score | due |
|---|---|---|
{stale_table}
""", encoding="utf-8")

    open_rows = conn.execute(
        """SELECT c.*, p.subject_id FROM contradictions c
           JOIN pages p ON p.page_id=c.page_id
           WHERE c.resolved_at IS NULL ORDER BY c.severity, c.detected_at"""
    ).fetchall()
    contra_lines = ["# Open contradictions", "", "tags: #contradiction", ""]
    if not open_rows:
        contra_lines.append("None — memory agrees with the code. ✅")
    for r in open_rows:
        contra_lines += [
            f"## [{r['contradiction_id']}] [[{_slug(r['subject_id'])}]] "
            f"({r['ctype']}, {r['severity']})",
            f"- claim: {r['claim']}",
            f"- truth: {r['truth']}",
            f"- resolve with: `irag resolve {r['contradiction_id']}`",
            "",
        ]
    (vault / "_meta" / "contradictions.md").write_text(
        "\n".join(contra_lines), encoding="utf-8")

    (vault / "_meta" / "graph_settings.md").write_text("""# Graph view setup (2 minutes)

1. Open this folder as a vault (File → Open Vault → Open folder as vault).
2. Open **Graph View** (Ctrl/Cmd+G).
3. Under **Groups**, add color groups in this order (first match wins):

| query | suggested color | meaning |
|---|---|---|
| `tag:#contradicted` | red | pages with open contradictions |
| `tag:#stale` | orange | pages past the staleness threshold |
| `tag:#version` | gray | revision-history chain nodes |
| `tag:#file` | green | file pages |
| `tag:#folder` | blue | folder overview pages |
| `tag:#decisions` | purple | the decisions log |


4. **The toggle trick:** type `-tag:#version` in the graph search box to
   hide version chains → clean module map. Clear it → full history graph,
   with gray chains hanging off every page.
5. `tag:#contradicted` in the search box highlights only unhealthy pages.

Regenerate the vault any time with `irag obsidian` (close the vault in
Obsidian first — it wipes and rebuilds the folder).
""", encoding="utf-8")

    index = ["# irag vault", "",
             "Read-only projection of `.irag/memory.db`. Do not edit — "
             "regenerate with `irag obsidian`.", "", "## Modules"]
    index += [f"- [[{_slug(p['subject_id'])}]]" for p in pages]
    index += ["", "## Meta", "- [[stats]]", "- [[contradictions]]",
              "- [[graph_settings]]"]
    (vault / "README.md").write_text("\n".join(index), encoding="utf-8")

    return vault
